"""Add doctor schedule fields

Revision ID: 0c71b4bae2bb
Revises: 21e13e134c26
Create Date: 2025-02-07 01:59:49.481648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c71b4bae2bb'
down_revision = '21e13e134c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_days', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('work_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('work_end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('break_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('break_end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('availability_notes', sa.Text(), nullable=True))
        batch_op.drop_column('availability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('availability_notes')
        batch_op.drop_column('is_available')
        batch_op.drop_column('break_end_time')
        batch_op.drop_column('break_start_time')
        batch_op.drop_column('work_end_time')
        batch_op.drop_column('work_start_time')
        batch_op.drop_column('working_days')

    # ### end Alembic commands ###
