"""Add priority queue fields to Admission model

Revision ID: 21e13e134c26
Revises: 
Create Date: 2025-02-07 01:02:10.723777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21e13e134c26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admission_backup')
    with op.batch_alter_table('admission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_level', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('priority_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('queue_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expected_duration', sa.Integer(), nullable=True))
        batch_op.alter_column('bed_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission', schema=None) as batch_op:
        batch_op.alter_column('bed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('expected_duration')
        batch_op.drop_column('queue_position')
        batch_op.drop_column('priority_score')
        batch_op.drop_column('priority_level')

    op.create_table('admission_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('discharge_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admission_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admission_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attending_doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
